### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [clee937/project-portfolio#1]
# Feedback

## Requirements:

1. A deployed website (using GitHub Pages)
2. A public GitHub repository for your codebase
3. Use HTML & SCSS
4. Make good use of semantic HTML elements
5. Be responsive (mobile-first) and built with accessibility in mind
6. Code is highly readable (good naming and indented correctly)

## Score

[MARKING-SCHEME](https://github.com/nology-tech/Waiheke-Course-Resources/blob/main/student-resources/01-web/marking-scheme.md)

| Category             | Score    |
| -------------------- | -------- |
| Site Output          | 35 / 50  |
| Responsiveness       | 15 / 15  |
| Code Knowledge & Use | 20 / 20  |
| Readability          | 15 / 15  |
| Version Control      | 0 / 10   |
| Total Score          | 85 / 110 |

### Positive

- Your project is great! it has been a good exercise for you to build a website from a wireframe.
  - If you ever need a break pick a website and try and recreate it.
- I am glad you pushed yourself by choosing to break your styles into multiple logical files.
  - Keep challenging yourself!
- It is good that you have added your profile picture, Keep on adding to the portfolio as you complete projects and have your profile completed.
- Great use of media queries, try using variables for the breakpoints in your next project.
  - `@media screen and (min-width: 900px) {}` -> `@media screen and (min-width: $tablet-breakpoint) {}`
- You are demonstrating a solid understanding of the majority of topics we have covered so far, keep it up and keep on using BEM, SCSS, grid and flex.

### Constructive

- You only have 5 commits :S

  - Try and get into the habit of regular commits at logical points in the project.
  - "Added project section HTML", "Added project section styling", "Updated project section media queries" etc...
  - One commit a day/afternoon at the very least!

- This is a minor point but try and be more consistent with your BEM & SCSS selectors. Try not to mix `&` and the use of the whole class name. When you have picked one follow this for the project so it is the same throughout.

```scss
// THE STYLES BELOW
.technical-skills {
  .technical-skills__logo-container {
  }

  .technical-skills__logo-text {
  }

  &__logo-and-text-container {
  }

  .technical-skills__logo-text {
  }

  .technical-skills__logo {
    path {
      fill: $primary-color;
    }
  }

  .technical-skills__logo--git:hover {
    path {
      fill: #e94d31;
    }
  }
}

// cOULD BE IF YOU ONLY USED THE &

.technical-skills {
  &__logo-container {
  }

  &__logo-text {
  }

  &__logo-and-text-container {
  }

  &__logo-text {
  }

  &__logo {
    path {
      fill: $primary-color;
    }
    // YOU NORMALLY HAVE THE MODIFIER INSIDE OF THE ELEMENT
    // - THIS MEANS WHEN YOU GO TO THE ELEMENT YOU CAN SEE ALL OF THE MODIFIERS
    &--git:hover path {
      // ^ SHOULD WORK BUT LET ME KNOW IF IT DOESN'T
      fill: #e94d31;
    }
  }
}
```

- It would be great if on the desktop the footer expanded across the whole screen. At the moment you limit the body's width and add margin and padding. If you removed this and then limited the width & added padding and margin to the main, nav, and header you could have the footer expand across the whole screen.

- You have a `.DS_Store` which you can delete, it gets autogenerated if you are working on a Mac. You can get git to ignore it by adding a `.gitignore` file to the repository.
  - If you add DS_Store to this file git will ignore it.
  - You can do this for each of your projects.

---
